[package]
name = "notary-server"
version.workspace = true
edition = "2024"
license = "MIT"
description = "Remote Proxy-TLS Notary server"

[features]
test-support = []

[[bin]]
name = "notary-server"
path = "src/bin/notary-server.rs"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
hex = { workspace = true }
k256 = { workspace = true, features = ["ecdsa"] }
libc = { workspace = true }
notary-core = { workspace = true }
metrics = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
